export const BUILDER_TITLES = [
  "Goa Vibe Coder 🌴",
  "Solana Warlock ⚡",
  "AI Agent Architect 🤖",
  "Zero Knowledge Druid 🧙‍♂️",
  "Prompt Wrangler 🤠",
  "Kernel Wizard 🔮",
  "Fullstack Alchemist 🧪",
  "DeFi Degenerate 📈",
  "Rust Byte Master 🦀",
  "Async Ninja 🥷",
  "Smart Contract Paladin 🛡️",
  "LLM Whisperer 🗣️",
  "Web3 Nomad 🏄‍♂️",
  "Hackathon Heavyweight 🏋️‍♂️",
  "Frontend Picasso 🎨",
  "Backend Titan 🏛️",
  "GPU Cluster Wrangler 💻",
  "Deep Tech Explorer 🧭",
  "Coffee-to-Code Converter ☕",
  "Late Night Commit Legend 🌙",
  "Bounty Hunter Supreme 🎯",
  "Vector Database Guru 🧠",
  "Consensus Crafter 📜",
  "Goa Sunset Hacker 🌅",
  "Vite Speed Demon ⚡",
  "GraphQL Oracle 👁️",
  "Docker Container King 🐳",
  "Postgres Optimizer 🐘",
  "CSS Pixel Sorcerer 🪄",
  "TypeScript Type Guard 🛡️",
  "Git Rebase Maverick 🔀",
  "Cyberpunk Hacker 🕶️",
  "Zero Bug Titan 🐛",
  "Sub-10ms Latency Boss ⏱️",
  "Neural Net Ninja 🧬",
  "Blockchain Nomad ⛓️",
  "Mainnet Warrior 🚀",
  "Gas Fee Saver ⛽",
  "Autonomous Agent Smith 🤖",
  "Hackathon Champion 🏆",
  "DevRel Magician 🪄",
  "Open Source Champion 🌐",
  "Infinite Loop Breaker 🔄",
  "Vercel Deploy God ☁️",
  "Terminal Overlord 🖥️",
  "State Management Sensei 🧘",
  "Payload Hacker 📦",
  "Crypto Cipher Master 🔑",
  "Solana TPU Whisperer ⚡",
  "Codebase Pathfinder 🗺️",
  "Memory Leak Catcher 💧",
  "UI/UX Mastermind 🎯",
  "Midnight Bug Hunter 🌌",
  "Syntactic Sugar Boss 🍬"
];

export const STACK_SUGGESTIONS = [
  "Fullstack & AI",
  "Rust & Solana",
  "React & Next.js",
  "Python & PyTorch",
  "TypeScript & Node",
  "Solidity & Web3",
  "Flutter & Mobile",
  "Go & Microservices"
];
